// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solvers.proto

package com.prma;

public final class Solvers {
  private Solvers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.prma.Solvers.SGDConfig.sgdConfig);
    registry.add(com.prma.Solvers.MultiSGDConfig.multiSgdConfig);
  }
  public interface SGDConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional float learning_rate = 1 [default = 0.1];
    boolean hasLearningRate();
    float getLearningRate();
    
    // optional float l2_regularization = 2 [default = 0.1];
    boolean hasL2Regularization();
    float getL2Regularization();
    
    // optional float l1_regularization = 3 [default = 0];
    boolean hasL1Regularization();
    float getL1Regularization();
  }
  public static final class SGDConfig extends
      com.google.protobuf.GeneratedMessage
      implements SGDConfigOrBuilder {
    // Use SGDConfig.newBuilder() to construct.
    private SGDConfig(Builder builder) {
      super(builder);
    }
    private SGDConfig(boolean noInit) {}
    
    private static final SGDConfig defaultInstance;
    public static SGDConfig getDefaultInstance() {
      return defaultInstance;
    }
    
    public SGDConfig getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prma.Solvers.internal_static_prma_SGDConfig_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prma.Solvers.internal_static_prma_SGDConfig_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional float learning_rate = 1 [default = 0.1];
    public static final int LEARNING_RATE_FIELD_NUMBER = 1;
    private float learningRate_;
    public boolean hasLearningRate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public float getLearningRate() {
      return learningRate_;
    }
    
    // optional float l2_regularization = 2 [default = 0.1];
    public static final int L2_REGULARIZATION_FIELD_NUMBER = 2;
    private float l2Regularization_;
    public boolean hasL2Regularization() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getL2Regularization() {
      return l2Regularization_;
    }
    
    // optional float l1_regularization = 3 [default = 0];
    public static final int L1_REGULARIZATION_FIELD_NUMBER = 3;
    private float l1Regularization_;
    public boolean hasL1Regularization() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getL1Regularization() {
      return l1Regularization_;
    }
    
    private void initFields() {
      learningRate_ = 0.1F;
      l2Regularization_ = 0.1F;
      l1Regularization_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, learningRate_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, l2Regularization_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, l1Regularization_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, learningRate_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, l2Regularization_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, l1Regularization_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.prma.Solvers.SGDConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.prma.Solvers.SGDConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.prma.Solvers.SGDConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.prma.Solvers.SGDConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.prma.Solvers.SGDConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.prma.Solvers.SGDConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.prma.Solvers.SGDConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.prma.Solvers.SGDConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.prma.Solvers.SGDConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.prma.Solvers.SGDConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.prma.Solvers.SGDConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.prma.Solvers.SGDConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prma.Solvers.internal_static_prma_SGDConfig_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prma.Solvers.internal_static_prma_SGDConfig_fieldAccessorTable;
      }
      
      // Construct using com.prma.Solvers.SGDConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        learningRate_ = 0.1F;
        bitField0_ = (bitField0_ & ~0x00000001);
        l2Regularization_ = 0.1F;
        bitField0_ = (bitField0_ & ~0x00000002);
        l1Regularization_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prma.Solvers.SGDConfig.getDescriptor();
      }
      
      public com.prma.Solvers.SGDConfig getDefaultInstanceForType() {
        return com.prma.Solvers.SGDConfig.getDefaultInstance();
      }
      
      public com.prma.Solvers.SGDConfig build() {
        com.prma.Solvers.SGDConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.prma.Solvers.SGDConfig buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.prma.Solvers.SGDConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.prma.Solvers.SGDConfig buildPartial() {
        com.prma.Solvers.SGDConfig result = new com.prma.Solvers.SGDConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.learningRate_ = learningRate_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.l2Regularization_ = l2Regularization_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.l1Regularization_ = l1Regularization_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prma.Solvers.SGDConfig) {
          return mergeFrom((com.prma.Solvers.SGDConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.prma.Solvers.SGDConfig other) {
        if (other == com.prma.Solvers.SGDConfig.getDefaultInstance()) return this;
        if (other.hasLearningRate()) {
          setLearningRate(other.getLearningRate());
        }
        if (other.hasL2Regularization()) {
          setL2Regularization(other.getL2Regularization());
        }
        if (other.hasL1Regularization()) {
          setL1Regularization(other.getL1Regularization());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              learningRate_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              l2Regularization_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              l1Regularization_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional float learning_rate = 1 [default = 0.1];
      private float learningRate_ = 0.1F;
      public boolean hasLearningRate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public float getLearningRate() {
        return learningRate_;
      }
      public Builder setLearningRate(float value) {
        bitField0_ |= 0x00000001;
        learningRate_ = value;
        onChanged();
        return this;
      }
      public Builder clearLearningRate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        learningRate_ = 0.1F;
        onChanged();
        return this;
      }
      
      // optional float l2_regularization = 2 [default = 0.1];
      private float l2Regularization_ = 0.1F;
      public boolean hasL2Regularization() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getL2Regularization() {
        return l2Regularization_;
      }
      public Builder setL2Regularization(float value) {
        bitField0_ |= 0x00000002;
        l2Regularization_ = value;
        onChanged();
        return this;
      }
      public Builder clearL2Regularization() {
        bitField0_ = (bitField0_ & ~0x00000002);
        l2Regularization_ = 0.1F;
        onChanged();
        return this;
      }
      
      // optional float l1_regularization = 3 [default = 0];
      private float l1Regularization_ ;
      public boolean hasL1Regularization() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getL1Regularization() {
        return l1Regularization_;
      }
      public Builder setL1Regularization(float value) {
        bitField0_ |= 0x00000004;
        l1Regularization_ = value;
        onChanged();
        return this;
      }
      public Builder clearL1Regularization() {
        bitField0_ = (bitField0_ & ~0x00000004);
        l1Regularization_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:prma.SGDConfig)
    }
    
    static {
      defaultInstance = new SGDConfig(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prma.SGDConfig)
    public static final int SGD_CONFIG_FIELD_NUMBER = 1001;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.prma.Structures.ModelConfig,
        com.prma.Solvers.SGDConfig> sgdConfig = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.prma.Solvers.SGDConfig.getDefaultInstance(),
          0,
          com.prma.Solvers.SGDConfig.class,
          com.prma.Solvers.SGDConfig.getDefaultInstance());
  }
  
  public interface MultiSGDConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional float learning_rate = 1 [default = 0.1];
    boolean hasLearningRate();
    float getLearningRate();
    
    // required int32 num_classes = 2 [default = 2];
    boolean hasNumClasses();
    int getNumClasses();
    
    // optional float l2_regularization = 3 [default = 0.1];
    boolean hasL2Regularization();
    float getL2Regularization();
    
    // optional float l1_regularization = 4 [default = 0];
    boolean hasL1Regularization();
    float getL1Regularization();
  }
  public static final class MultiSGDConfig extends
      com.google.protobuf.GeneratedMessage
      implements MultiSGDConfigOrBuilder {
    // Use MultiSGDConfig.newBuilder() to construct.
    private MultiSGDConfig(Builder builder) {
      super(builder);
    }
    private MultiSGDConfig(boolean noInit) {}
    
    private static final MultiSGDConfig defaultInstance;
    public static MultiSGDConfig getDefaultInstance() {
      return defaultInstance;
    }
    
    public MultiSGDConfig getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prma.Solvers.internal_static_prma_MultiSGDConfig_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prma.Solvers.internal_static_prma_MultiSGDConfig_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional float learning_rate = 1 [default = 0.1];
    public static final int LEARNING_RATE_FIELD_NUMBER = 1;
    private float learningRate_;
    public boolean hasLearningRate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public float getLearningRate() {
      return learningRate_;
    }
    
    // required int32 num_classes = 2 [default = 2];
    public static final int NUM_CLASSES_FIELD_NUMBER = 2;
    private int numClasses_;
    public boolean hasNumClasses() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getNumClasses() {
      return numClasses_;
    }
    
    // optional float l2_regularization = 3 [default = 0.1];
    public static final int L2_REGULARIZATION_FIELD_NUMBER = 3;
    private float l2Regularization_;
    public boolean hasL2Regularization() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getL2Regularization() {
      return l2Regularization_;
    }
    
    // optional float l1_regularization = 4 [default = 0];
    public static final int L1_REGULARIZATION_FIELD_NUMBER = 4;
    private float l1Regularization_;
    public boolean hasL1Regularization() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getL1Regularization() {
      return l1Regularization_;
    }
    
    private void initFields() {
      learningRate_ = 0.1F;
      numClasses_ = 2;
      l2Regularization_ = 0.1F;
      l1Regularization_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNumClasses()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, learningRate_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, numClasses_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, l2Regularization_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, l1Regularization_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, learningRate_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numClasses_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, l2Regularization_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, l1Regularization_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.prma.Solvers.MultiSGDConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.prma.Solvers.MultiSGDConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.prma.Solvers.MultiSGDConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.prma.Solvers.MultiSGDConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.prma.Solvers.MultiSGDConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.prma.Solvers.MultiSGDConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.prma.Solvers.MultiSGDConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.prma.Solvers.MultiSGDConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.prma.Solvers.MultiSGDConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.prma.Solvers.MultiSGDConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.prma.Solvers.MultiSGDConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.prma.Solvers.MultiSGDConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prma.Solvers.internal_static_prma_MultiSGDConfig_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prma.Solvers.internal_static_prma_MultiSGDConfig_fieldAccessorTable;
      }
      
      // Construct using com.prma.Solvers.MultiSGDConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        learningRate_ = 0.1F;
        bitField0_ = (bitField0_ & ~0x00000001);
        numClasses_ = 2;
        bitField0_ = (bitField0_ & ~0x00000002);
        l2Regularization_ = 0.1F;
        bitField0_ = (bitField0_ & ~0x00000004);
        l1Regularization_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prma.Solvers.MultiSGDConfig.getDescriptor();
      }
      
      public com.prma.Solvers.MultiSGDConfig getDefaultInstanceForType() {
        return com.prma.Solvers.MultiSGDConfig.getDefaultInstance();
      }
      
      public com.prma.Solvers.MultiSGDConfig build() {
        com.prma.Solvers.MultiSGDConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.prma.Solvers.MultiSGDConfig buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.prma.Solvers.MultiSGDConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.prma.Solvers.MultiSGDConfig buildPartial() {
        com.prma.Solvers.MultiSGDConfig result = new com.prma.Solvers.MultiSGDConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.learningRate_ = learningRate_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.numClasses_ = numClasses_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.l2Regularization_ = l2Regularization_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.l1Regularization_ = l1Regularization_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prma.Solvers.MultiSGDConfig) {
          return mergeFrom((com.prma.Solvers.MultiSGDConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.prma.Solvers.MultiSGDConfig other) {
        if (other == com.prma.Solvers.MultiSGDConfig.getDefaultInstance()) return this;
        if (other.hasLearningRate()) {
          setLearningRate(other.getLearningRate());
        }
        if (other.hasNumClasses()) {
          setNumClasses(other.getNumClasses());
        }
        if (other.hasL2Regularization()) {
          setL2Regularization(other.getL2Regularization());
        }
        if (other.hasL1Regularization()) {
          setL1Regularization(other.getL1Regularization());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNumClasses()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              learningRate_ = input.readFloat();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              numClasses_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              l2Regularization_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              l1Regularization_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional float learning_rate = 1 [default = 0.1];
      private float learningRate_ = 0.1F;
      public boolean hasLearningRate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public float getLearningRate() {
        return learningRate_;
      }
      public Builder setLearningRate(float value) {
        bitField0_ |= 0x00000001;
        learningRate_ = value;
        onChanged();
        return this;
      }
      public Builder clearLearningRate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        learningRate_ = 0.1F;
        onChanged();
        return this;
      }
      
      // required int32 num_classes = 2 [default = 2];
      private int numClasses_ = 2;
      public boolean hasNumClasses() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getNumClasses() {
        return numClasses_;
      }
      public Builder setNumClasses(int value) {
        bitField0_ |= 0x00000002;
        numClasses_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumClasses() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numClasses_ = 2;
        onChanged();
        return this;
      }
      
      // optional float l2_regularization = 3 [default = 0.1];
      private float l2Regularization_ = 0.1F;
      public boolean hasL2Regularization() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getL2Regularization() {
        return l2Regularization_;
      }
      public Builder setL2Regularization(float value) {
        bitField0_ |= 0x00000004;
        l2Regularization_ = value;
        onChanged();
        return this;
      }
      public Builder clearL2Regularization() {
        bitField0_ = (bitField0_ & ~0x00000004);
        l2Regularization_ = 0.1F;
        onChanged();
        return this;
      }
      
      // optional float l1_regularization = 4 [default = 0];
      private float l1Regularization_ ;
      public boolean hasL1Regularization() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getL1Regularization() {
        return l1Regularization_;
      }
      public Builder setL1Regularization(float value) {
        bitField0_ |= 0x00000008;
        l1Regularization_ = value;
        onChanged();
        return this;
      }
      public Builder clearL1Regularization() {
        bitField0_ = (bitField0_ & ~0x00000008);
        l1Regularization_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:prma.MultiSGDConfig)
    }
    
    static {
      defaultInstance = new MultiSGDConfig(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prma.MultiSGDConfig)
    public static final int MULTI_SGD_CONFIG_FIELD_NUMBER = 1002;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.prma.Structures.ModelConfig,
        com.prma.Solvers.MultiSGDConfig> multiSgdConfig = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.prma.Solvers.MultiSGDConfig.getDefaultInstance(),
          0,
          com.prma.Solvers.MultiSGDConfig.class,
          com.prma.Solvers.MultiSGDConfig.getDefaultInstance());
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prma_SGDConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prma_SGDConfig_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prma_MultiSGDConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prma_MultiSGDConfig_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsolvers.proto\022\004prma\032\013model.proto\"\236\001\n\tS" +
      "GDConfig\022\032\n\rlearning_rate\030\001 \001(\002:\0030.1\022\036\n\021" +
      "l2_regularization\030\002 \001(\002:\0030.1\022\034\n\021l1_regul" +
      "arization\030\003 \001(\002:\001027\n\nsgd_config\022\021.prma." +
      "ModelConfig\030\351\007 \001(\0132\017.prma.SGDConfig\"\306\001\n\016" +
      "MultiSGDConfig\022\032\n\rlearning_rate\030\001 \001(\002:\0030" +
      ".1\022\026\n\013num_classes\030\002 \002(\005:\0012\022\036\n\021l2_regular" +
      "ization\030\003 \001(\002:\0030.1\022\034\n\021l1_regularization\030" +
      "\004 \001(\002:\00102B\n\020multi_sgd_config\022\021.prma.Mode" +
      "lConfig\030\352\007 \001(\0132\024.prma.MultiSGDConfigB\023\n\010",
      "com.prmaB\007Solvers"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_prma_SGDConfig_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_prma_SGDConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prma_SGDConfig_descriptor,
              new java.lang.String[] { "LearningRate", "L2Regularization", "L1Regularization", },
              com.prma.Solvers.SGDConfig.class,
              com.prma.Solvers.SGDConfig.Builder.class);
          internal_static_prma_MultiSGDConfig_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_prma_MultiSGDConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prma_MultiSGDConfig_descriptor,
              new java.lang.String[] { "LearningRate", "NumClasses", "L2Regularization", "L1Regularization", },
              com.prma.Solvers.MultiSGDConfig.class,
              com.prma.Solvers.MultiSGDConfig.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.prma.Structures.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
